name: Newman/newmanParallelAPIsTests
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      test_env:
        type: choice
        description: "environment"
        required: true
        default: 'uat'
        options:
          - 'uat'
          - 'prod'

jobs:
  newman-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        collection: [ReqResCollection, fetches]  
    continue-on-error: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Newman, Allure, and Allure Reporter for Newman
      run: |
        npm install -g newman
        npm install -g allure-commandline --save-dev
        npm install -g newman-reporter-allure

    - name: Run Newman Tests
      run: |
        mkdir -p allure-results-${{ matrix.collection }}  
        chmod -R 777 ./allure-results-${{ matrix.collection }}  
        newman run ${{ matrix.collection }}.postman_collection.json -r cli,allure --reporter-allure-export ./allure-results-${{ matrix.collection }} 
    - name: Move Allure files to target directory
      run: mv ./allure-results/* ./allure-results-${{ matrix.collection }}/
    - name: List files
      run: |
        ls -R
        ls -R ./allure-results-${{ matrix.collection }}
    - name: Upload Allure Results as Artifact
      if: success() || failure()  # Ensure this step runs even if the tests fail
      uses: actions/upload-artifact@v4
      with:
        name: allure-results-${{ matrix.collection }}
        path: ./allure-results-${{ matrix.collection }}
  generate-allure-report:
    needs: newman-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        collection: [ReqResCollection, fetches]  
    if: always()

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download Allure Results
      uses: actions/download-artifact@v4
      with:
        name: allure-results
        path: ./allure-results-temp

    - name: Merge Allure Results
      run: |
        npm install -g allure-commandline --save-dev
        mkdir -p merged-results
        find ./allure-results-temp -type f -exec cp {} merged-results/ \;

    - name: Generate Allure Report
      run: |
        allure generate merged-results --clean -o ./allure-report-${{ matrix.collection }}

    - name: Deploy Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./allure-report

    - name: Add Allure Report URL to Summary
      uses: actions/github-script@v7
      with:
        script: |
          const repo = context.repo;
          const reportUrl = `https://${repo.owner}.github.io/${repo.repo}/index.html`;
          core.summary.addRaw(`### :tada: `)
                      .addLink(`View Allure Report`, reportUrl)
                      .write();
