name: Newman/APItests

on: 
  push:
    branches: [ main ]
  schedule:
    - cron:  '30 5,17 * * *'
  
jobs:
  build:
    runs-on: ubuntu-latest 
    strategy: 
      matrix:
        node-version: [14]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1 
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install newman 
        run: |
          npm install -g bootstrap@4.0.0-alpha.6
          npm install -g newman
          npm install -g newman 
          npm install -g newman-reporter-htmlextra
      - name: Make Directory for results 
        run: mkdir -p testResults
      - name: Run articles collection 
        if: always() 
        run: newman run "ReqResCollection.postman_collection.json" 
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: api_tests
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: 'API tests executed was failed'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        if: always()   
