name: Newman/ParallelAPItestsWorks1
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      test_env:
        type: choice
        description: "environment"
        required: true
        default: 'uat'
        options:
          - 'uat'
          - 'prod'
jobs:
  newman-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        collection: 
          - ReqResCollection
          - fetches
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Newman and Allure Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-allure

      - name: Run Newman Collection
        run: |
          mkdir -p ./allure-results-${{ matrix.collection }}
          newman run ${{ matrix.collection }}.postman_collection.json -r allure --reporter-allure-export ./allure-results-${{ matrix.collection }}
      
      - name: Upload Allure results as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: allure-results-${{ matrix.collection }}
          path: ./allure-results-${{ matrix.collection }}

  generate-allure-report:
    needs: newman-tests
    runs-on: ubuntu-latest
    steps:
      - name: Download Allure results
        uses: actions/download-artifact@v3
        with:
          name: allure-results-ReqResCollection
          path: ./merged-allure-results

      - name: Download Allure results
        uses: actions/download-artifact@v3
        with:
          name: allure-results-fetches
          path: ./merged-allure-results

      - name: Generate Allure Report
        run: |
          npm install -g allure-commandline --save-dev
          allure generate ./merged-allure-results --clean -o ./allure-report
          
      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: ./allure-report

      - name: Publish Allure Report
        if: always()
        uses: actions/github-pages@v3
        with:
          publish_dir: ./allure-report
